name: time_sheet
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: dmarl <email@example.com>
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  intl: ^0.15.1
  sass_builder: ^1.0.1
  grid:
    git: git://github.com/afpatmin/Grid
  fo_components:
    git: git://github.com/afpatmin/FoComponents
  serializable: ^0.7.1
  vi_auth_client:
    git: git://github.com/afpatmin/ViAuthClient
  http: ^0.11.3+16

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- sass_builder:
    outputExtension: .css
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter
web:
 compiler:
     debug: dartdevc
